Pagination
banyan-team/banyan-julia pull request #31
Opened 2021-09-27 17:33 UTC by clarisw

2021-09-27 19:46 UTC, calebwin requested changes
Looks good overall, just a few comments. If you can resolve these, it would be great to merge this in soon - it's causing some issues with the tests I'm trying to run which I then need to work around.

2021-09-27 19:46 UTC, calebwin commented on Banyan/src/utils.jl
> +    @show banyan_config
@clarisw Can you please remove this?

2021-09-27 19:46 UTC, calebwin commented on Banyan/src/jobs.jl
>  	    response["jobs"][id]["ended"] = nothing
Make sure you have good formatting here and elsewhere

2021-09-28 01:56 UTC, cailinw requested changes

2021-09-28 01:56 UTC, cailinw commented on Banyan/src/jobs.jl
> +    # finished = false
nit: remove

2021-09-28 01:56 UTC, cailinw commented on Banyan/src/jobs.jl
> +    response = Dict("last_eval_key" => 50394, "jobs" => [])
Why is this variable `response` getting set here? It seems that it gets set on line 221, and I think that should be sufficient?

2021-09-28 01:56 UTC, cailinw commented on Banyan/src/jobs.jl
> +    if indiv_response["last_eval"] == nothing
Julia has a function to check if something is nothing. `isnothing()`
Here, you can do something like `if isnothing(indiv_response["last_eval"])`

2021-09-28 01:56 UTC, cailinw commented on Banyan/src/jobs.jl
> +            println(curr_last_eval)
Maybe we can put this in an `if is_debug()` if statement, so that we only print this out if we are in debug mode.

2021-09-28 01:56 UTC, cailinw commented on Banyan/src/jobs.jl
> +            if indiv_response["last_eval"] == nothing
Again, you can use `isnothing()` here as well

2021-09-28 06:30 UTC, clarisw commented on Banyan/src/jobs.jl
> +    response = Dict("last_eval_key" => 50394, "jobs" => [])
I set it there to initialize the keys and the dictionary...

2021-09-28 07:23 UTC, cailinw commented on Banyan/src/jobs.jl
> +    response = Dict("last_eval_key" => 50394, "jobs" => [])
I see. I agree it isn't necessary, since the whole variable gets reassigned in a later line.

2021-09-28 07:24 UTC, cailinw approved these changes

2021-09-28 07:24 UTC, merged