Add tests for empty DataFrames
banyan-team/banyan-julia pull request #59
Opened 2021-10-17 06:13 UTC by cailinw

* Test reading in an empty file (blank file with no contents) and writing it out
* (1) but with an empty directory
* Test filtering a CSV dataset (so that its empty) and then writing the result to a file
* Test fFiltering a CSV dataset (so that its empty) and then doing a groupby-subset and writing the result to a file
* (3) and (4) but filtering to a single row
* Test getting a column (which would be a Banyan array) and collecting a reduce (using init) result?

All of the above should for the 3 different kinds of scheduling_configs and for the 3 kinds of files (csv, parquet, arrow)

2021-10-17 15:07 UTC, calebwin requested changes
Looks good overall. Have you tested this on empty data? Some libraries don't really support certain operations - like I don't think HDF5.jl can read in an empty dataset but CSV.jl can read in an empty file... have you checked that what you're testing should actually work?

2021-10-17 15:07 UTC, calebwin commented on BanyanDataFrames/test/runtests.jl
> +end
You need to make sure that this function (and other `use_*` functions) can be called multiple times without work being repeatedly done. It doesn't look like `setup_empty_tests` is like that but is it?

2021-10-18 00:21 UTC, cailinw commented on BanyanDataFrames/test/runtests.jl
> +end
Oh, hmm...I don't think `setup_empty_tests` does that. I can change that.

2021-10-18 00:22 UTC, cailinw commented
I have tested it in the repl with an empty df, but I haven't tested in reading an empty file. Also, these tests don't use HDF5.jl directly, I think. I double check that reading it works

2021-10-19 00:50 UTC, calebwin approved these changes

2021-10-19 00:50 UTC, merged